# Generated by Django 4.0.6 on 2022-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('NE', 'news'), ('AR', 'article')], default='NE', max_length=2),
        ),
    ]
